name: Test games

on:
  push:
    branches:
      - master

jobs:
  run_hangman_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run : |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run account app tests
      run: |
        python -m unittest discover
